name: warehousesys
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1
  intl: ^0.20.2
  freezed_annotation: ^2.4.1
  phosphor_flutter: ^2.1.0
  json_annotation: ^4.9.0

  cupertino_icons: ^1.0.8
  flutter_gen: ^5.12.0

  path_provider: ^2.1.2
  open_filex: ^4.3.2
  file_saver: ^0.2.14
  permission_handler: ^11.3.0
  share_plus: ^10.0.0

  printing: ^5.11.0
  pdf: ^3.10.0

  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

  flutter_lints: ^5.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont.ttf
          style: italic